### ISSUE TITLE
ขอเสนอ jtcc ครับ

### ISSUE THREAD

**Issue by wittawatj** [xbklairith/Awesome-Thai-Library#1]
jtcc เป็นไลบราลี่ ภาษา Java เอาไว้ตัด string ให้เป็นหน่วยที่เรียกว่า TCC (ไม่ใช่คำ เล็กกว่าคำ) คือกลุ่มของอักษรที่แยกจากกันไม่ได้ตามกฎการเขียนภาษาไทย https://github.com/wittawatj/jtcc เขียนไว้นานแล้วจนผู้เขียนก็เริ่มเลืมแล้ว แต่อาจจะพอเป็นประโยชน์อยู่

**Comment by xbklairith** [comment]
+ เพิ่มแล้วครับ น่าจะมีประโยชน์ตอนตัดคำในกรณีที่ มีการพิมพ์ผิด
ขอบคุณครับ
